The developers might have had a small bug in the first week that could have affected the user experience for those users who sent a free tree.
The task is to create a cohort analysis and check the retention numbers of those users who sent their first free_tree during this period (between Sep 13, 2019 and Sep 19, 2019) and compare it to the retention numbers of other cohorts of users who sent their first free_tree when the product was fixed (e.g. between Sep 20, 2019 and Sep 26, 2019).
This cohort analysis is aimed to investigate whether the users have returned in any of the first 7 days after their first free_tree send.
When the analysis is performed, it is to be visualized in Google Data Studio.

In [165]:
import csv
from datetime import date
from datetime import timedelta 
import pandas as pd

In [166]:
user_sends = {}
with open('/home/dataguy/free_tree/first21_free.csv') as csvfile:
    readCSV = csv.reader(csvfile, delimiter=' ')
    for row in readCSV:
        if row[2] not in user_sends:
            user_sends[row[2]] = []
        if row[1] not in user_sends[row[2]]:    
            user_sends[row[2]].append(row[1])

In [168]:
user_sends_list = list(user_sends.values())

In [159]:
#a function to convert dates from the datetime format to the string 
def conv_date_str(dt):
    if dt.month<10: #some entries here to make sure we get a standardized output with zeroes in months and days
        return str(dt.year)+'-0'+str(dt.month)+'-'+str(dt.day)
    elif dt.day<10:
        return str(dt.year)+'-'+str(dt.month)+'-0'+str(dt.day)
    elif dt.month<10 and dt.day<10:
        return str(dt.year)+'-0'+str(dt.month)+'-0'+str(dt.day)
    else:
        return str(dt.year)+'-'+str(dt.month)+'-'+str(dt.day)

In [51]:
#a function to convert dates from the string format to the datetime to make date calculations simpler 
def conv_date(dt):
    year = int(dt[:4])
    month = int(dt[5:7])
    day = int(dt[8:])
    return date(year,month,day)

In [52]:
#a function that calculates the day differnce between two dates
def daydelta(dt1,dt2):
    x = conv_date(dt1)
    y = conv_date(dt2)
    delta = x - y
    return delta.days

In [160]:
#creating a list of dates (start date - Sep 13, 2019)
date_list = []
x = date(2019,9,13)
for i in range(0,21):
    date_list.append(conv_date_str(x))
    x=x+timedelta(days=1)

In [172]:
count=0
cohort_sum = pd.DataFrame(columns=['cohort','days_passed','number_of_users']) #creating the dataframe
for cohort in date_list[0:14]: #cohorts of the first two weeks
    for i in range(0,8): #days passed since the original cohort date
        count = 0
        for j in range(0,len(user_sends_list)): #checking the number of comebacks
            if (date_list[i+date_list.index(cohort)] in user_sends_list[j]) and (user_sends_list[j][0]==cohort):
                count+=1
        row = {'cohort':cohort, 'days_passed':daydelta(date_list[i+date_list.index(cohort)],cohort), 'number_of_users':count}
        cohort_sum = cohort_sum.append(row, ignore_index=True)

In [173]:
cohort_sum

         cohort days_passed number_of_users
0    2019-09-13           0              78
1    2019-09-13           1              58
2    2019-09-13           2              37
3    2019-09-13           3              33
4    2019-09-13           4              25
5    2019-09-13           5              29
6    2019-09-13           6              28
7    2019-09-13           7              27
8    2019-09-14           0              66
9    2019-09-14           1              42
10   2019-09-14           2              31
11   2019-09-14           3              18
12   2019-09-14           4              19
13   2019-09-14           5              17
14   2019-09-14           6              18
15   2019-09-14           7              21
16   2019-09-15           0              65
17   2019-09-15           1              53
18   2019-09-15           2              33
19   2019-09-15           3              30
20   2019-09-15           4              27
21   2019-09-15           5              25
22   2019-09-15           6              22
23   2019-09-15           7              21
24   2019-09-16           0              91
25   2019-09-16           1              77
26   2019-09-16           2              45
27   2019-09-16           3              42
28   2019-09-16           4              34
29   2019-09-16           5              30
..          ...         ...             ...
82   2019-09-23           2              42
83   2019-09-23           3              34
84   2019-09-23           4              37
85   2019-09-23           5              26
86   2019-09-23           6              30
87   2019-09-23           7              26
88   2019-09-24           0             110
89   2019-09-24           1              83
90   2019-09-24           2              50
91   2019-09-24           3              36
92   2019-09-24           4              42
93   2019-09-24           5              38
94   2019-09-24           6              37
95   2019-09-24           7              37
96   2019-09-25           0             107
97   2019-09-25           1              78
98   2019-09-25           2              45
99   2019-09-25           3              42
100  2019-09-25           4              40
101  2019-09-25           5              38
102  2019-09-25           6              37
103  2019-09-25           7              35
104  2019-09-26           0             104
105  2019-09-26           1              78
106  2019-09-26           2              42
107  2019-09-26           3              45
108  2019-09-26           4              36
109  2019-09-26           5              42
110  2019-09-26           6              38
111  2019-09-26           7              37

[112 rows x 3 columns]

In [164]:
#exporting the data to a csv file
cohort_sum.to_csv('/home/dataguy/practice/cohort_analysis.csv')